###

# Add user3 purchase

POST http://localhost:10000/payment/mastercheif.workplace@gmail.com
Content-Type: application/json

{
"name":"S235 Ultra",
"amount":100000,
"saving":200,
"img":"localhost",
"month":4,
"year":2024,
"tag":"mobile"
}


###

#Check user1 budget threshold

GET http://localhost:10000/budget/threshold/19it103@charusat.edu.in



###

# update user1 budget threshold

PUT http://localhost:10000/budget/threshold/19it103@charusat.edu.in
Content-Type: application/json

{
"month":30000,
"year":50000
}


###

#Check user1 budget threshold

GET http://localhost:10000/budget/threshold/19i


###


#get purchase history of year

POST http://localhost:10000/history/year/sukesssss1254a@gmail.com
Content-Type: application/json

{
"year":2024
}

###

#get purchase history of month

POST http://localhost:10000/history/month/sukesssss1254a@gmail.com
Content-Type: application/json

{
"month":3,
"year":2024
}


###

#get purchase history of month by tag

POST http://localhost:10000/history/month/sukesssss1254a@gmail.com/tag
Content-Type: application/json

{
"month":4,
"year":2024,
"tag":"electronic"
}


###

#get purchase history of month by tag

POST http://localhost:10000/history/year/sukesssss1254a@gmail.com/tag
Content-Type: application/json

{
"year":2024,
"tag":"electronic"
}
